#!/usr/bin/env bash
# =============================================================================
# KnewSearch AEO Visibility Platform - GCP Bootstrap Script
# =============================================================================
# This script enables the required GCP APIs and sets up initial configuration
# for the KnewSearch platform.
#
# Usage:
#   ./scripts/gcp_bootstrap.sh <project-id> [region]
#
# Example:
#   ./scripts/gcp_bootstrap.sh my-knewsearch-project us-central1
# =============================================================================

set -euo pipefail

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Logging functions
log_info() {
    echo -e "${BLUE}[INFO]${NC} $1"
}

log_success() {
    echo -e "${GREEN}[SUCCESS]${NC} $1"
}

log_warning() {
    echo -e "${YELLOW}[WARNING]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

# Check if required tools are installed
check_prerequisites() {
    log_info "Checking prerequisites..."

    if ! command -v gcloud &> /dev/null; then
        log_error "gcloud CLI is not installed. Please install it from https://cloud.google.com/sdk/docs/install"
        exit 1
    fi

    if ! command -v terraform &> /dev/null; then
        log_error "Terraform is not installed. Please install it from https://www.terraform.io/downloads"
        exit 1
    fi

    log_success "Prerequisites check passed"
}

# Parse arguments
if [ $# -lt 1 ]; then
    log_error "Usage: $0 <project-id> [region]"
    log_info "Example: $0 my-knewsearch-project us-central1"
    exit 1
fi

PROJECT_ID="${1}"
REGION="${2:-us-central1}"

log_info "=================================================="
log_info "KnewSearch GCP Bootstrap"
log_info "=================================================="
log_info "Project ID: ${PROJECT_ID}"
log_info "Region: ${REGION}"
log_info "=================================================="

# Check prerequisites
check_prerequisites

# Set the project
log_info "Setting GCP project to ${PROJECT_ID}..."
gcloud config set project "${PROJECT_ID}"

# Check if user is authenticated
if ! gcloud auth list --filter="status:ACTIVE" --format="value(account)" | grep -q .; then
    log_error "Not authenticated with gcloud. Please run: gcloud auth login"
    exit 1
fi

# Check if user has necessary permissions
log_info "Checking project permissions..."
if ! gcloud projects describe "${PROJECT_ID}" &> /dev/null; then
    log_error "Cannot access project ${PROJECT_ID}. Please check permissions."
    exit 1
fi

# Enable required APIs
log_info "Enabling required GCP APIs..."

APIS=(
    # Core services
    "cloudresourcemanager.googleapis.com"
    "iam.googleapis.com"
    "iamcredentials.googleapis.com"

    # Compute and runtime
    "run.googleapis.com"
    "containerregistry.googleapis.com"
    "artifactregistry.googleapis.com"
    "cloudbuild.googleapis.com"

    # Data and messaging
    "bigquery.googleapis.com"
    "pubsub.googleapis.com"

    # Scheduling
    "cloudscheduler.googleapis.com"

    # AI/ML
    "aiplatform.googleapis.com"
    "generativelanguage.googleapis.com"

    # Security
    "secretmanager.googleapis.com"

    # Monitoring and logging
    "logging.googleapis.com"
    "monitoring.googleapis.com"
    "cloudtrace.googleapis.com"
)

for api in "${APIS[@]}"; do
    log_info "Enabling ${api}..."
    gcloud services enable "${api}" --project="${PROJECT_ID}" || {
        log_warning "Failed to enable ${api}, continuing..."
    }
done

log_success "All APIs enabled successfully"

# Create Artifact Registry repository (for container images)
log_info "Creating Artifact Registry repository..."
REPO_NAME="knewsearch"

if gcloud artifacts repositories describe "${REPO_NAME}" --location="${REGION}" --project="${PROJECT_ID}" &> /dev/null; then
    log_info "Artifact Registry repository '${REPO_NAME}' already exists"
else
    gcloud artifacts repositories create "${REPO_NAME}" \
        --repository-format=docker \
        --location="${REGION}" \
        --description="KnewSearch container images" \
        --project="${PROJECT_ID}"
    log_success "Created Artifact Registry repository: ${REPO_NAME}"
fi

# Configure Docker for Artifact Registry
log_info "Configuring Docker authentication for Artifact Registry..."
gcloud auth configure-docker "${REGION}-docker.pkg.dev" --quiet

# Create terraform.tfvars if it doesn't exist
TFVARS_FILE="infra/terraform/terraform.tfvars"
if [ ! -f "${TFVARS_FILE}" ]; then
    log_info "Creating ${TFVARS_FILE}..."
    cat > "${TFVARS_FILE}" << EOF
# KnewSearch Terraform Configuration
# Generated by gcp_bootstrap.sh on $(date)

project_id = "${PROJECT_ID}"
region     = "${REGION}"
environment = "dev"

# BigQuery
bigquery_dataset_id = "knewsearch_aeo"
bigquery_location   = "US"

# Cloud Run Images (update after building)
prompt_runner_image    = "${REGION}-docker.pkg.dev/${PROJECT_ID}/${REPO_NAME}/prompt-runner:latest"
answer_generator_image = "${REGION}-docker.pkg.dev/${PROJECT_ID}/${REPO_NAME}/answer-generator:latest"
parser_image           = "${REGION}-docker.pkg.dev/${PROJECT_ID}/${REPO_NAME}/parser:latest"

# Cloud Run Resources
cloud_run_cpu           = "1"
cloud_run_memory        = "512Mi"
cloud_run_max_instances = 10
log_level               = "INFO"

# Cloud Scheduler
daily_run_schedule      = "0 6 * * *"
weekly_summary_schedule = "0 8 * * 1"
scheduler_timezone      = "America/Chicago"

# AI/ML
gemini_model        = "gemini-1.5-pro"
embedding_model     = "text-embedding-004"
embedding_dimension = 768
EOF
    log_success "Created ${TFVARS_FILE}"
else
    log_warning "${TFVARS_FILE} already exists, skipping..."
fi

# Initialize Terraform
log_info "Initializing Terraform..."
cd infra/terraform
terraform init

log_success "=================================================="
log_success "GCP Bootstrap Complete!"
log_success "=================================================="
echo ""
log_info "Next steps:"
echo "  1. Add your Gemini API key to Secret Manager:"
echo "     gcloud secrets versions add knewsearch-gemini-api-key --data-file=<path-to-api-key>"
echo ""
echo "  2. Build and push container images:"
echo "     docker build -t ${REGION}-docker.pkg.dev/${PROJECT_ID}/${REPO_NAME}/prompt-runner:latest services/prompt_runner"
echo "     docker push ${REGION}-docker.pkg.dev/${PROJECT_ID}/${REPO_NAME}/prompt-runner:latest"
echo "     # Repeat for answer_generator and parser"
echo ""
echo "  3. Review and apply Terraform:"
echo "     cd infra/terraform"
echo "     terraform plan"
echo "     terraform apply"
echo ""
echo "  4. See docs/deploy.md for full deployment instructions"
